### ISSUE TITLE
生成的Tags重复

### ISSUE THREAD

**Issue by Xuanwo** [ppoffice/hexo-theme-alex#3]
不知道是hexo的问题还是主题的问题= =

https://github.com/hexojs/hexo/issues/1035

**Comment by ppoffice** [comment]
```shell
hexo clean
```
Hexo的服务器有时候会抽筋一下

**Comment by Xuanwo** [comment]
2333，唉= =，试过很多次了还是有，蛋疼。
不过那边好像确认为BUG了，再等等吧

**Comment by Xuanwo** [comment]
已修复
