### ISSUE TITLE
Share one friendly & Fun Javascript Fullstack  MEAN(MongoDB, Express, Angular and Node)

### ISSUE THREAD

**Issue by PhilipsYuan** [ppoffice/hexo-theme-alex#8]
借着晴姐的这篇blog, 我也分享一个Javascript Fullstack -- MEAN. 我之前用这个做过一个小项目。
这个框架就是用 MongoDB, Express, Angular 和 Node 去实现一个web application.
具体的信息可以去这里查看：
http://mean.io/#!/

**Comment by ppoffice** [comment]
请不要在这里发广告
